### PR TITLE
Use Symfony Mailer instead of SwiftMailer

### PR DESCRIPTION
**Pull request by szymach**
Solves #136

### CODE REVIEW

**Comment by szymach** [comment]
@fsi-open

**Comment by szymach** [comment]
@fsi-open

**Review by chives — APPROVED** [review]

**Comment by szymach** [comment]
@fsi-open

**Review by chives — APPROVED** [review]

**Comment by szymach** [comment]
@rn0

**Review by rn0 — APPROVED** [review]

**Pull request merged**
