### PR TITLE
Remove fosub

### PR DESCRIPTION
**Pull request by chives**
Updated version of #32

### CODE REVIEW

**Comment by chives** [comment]
@fsi-open this is former #32 merged with current master

**Comment by szymach** [comment]
perhaps we can close #32 then?

**Comment by szymach** [comment]
why the safer composer cache change?

**Comment by chives** [comment]
caching `vendor` dir causes troubles when installing different version of symfony than previously cached by travis

**Comment by JarekW** [comment]
it's 8,5k+ we cannot check this thoroughly, is it wailing for something?

**Comment by szymach** [comment]
http://ling.pl/wail

**Comment by szymach** [comment]
:+1:

**Comment by szymach** [comment]
merging this shit

**Pull request merged**
