### PR TITLE
Fix doc for creating user command

### PR DESCRIPTION
**Pull request by partikus**
In the description you mentioned username argument:
``php app/console fsi:user:create john john@example.com mypassword ROLE_ADMIN``

I've added ``username`` argument.

@fsi-open ping

### CODE REVIEW

**Comment by partikus** [comment]
@chives @rn0 could you rerun build?

**Comment by JarekW** [comment]
:+1:

**Comment by szymach** [comment]
well you removed the `username` argument from the doc, not added it, but :+1: still :P

**Comment by partikus** [comment]
@szymach you're right. Finally I removed the command fix and keep only @chives suggestion. I can revert that but does it make sense?

**Comment by szymach** [comment]
I think it's OK now

**Comment by chives** [comment]
:+1:

**Pull request merged**
