### PR TITLE
Change admin-bundle dependency to ~2.0@dev

### PR DESCRIPTION
**Pull request by szymach**

### CODE REVIEW

**Comment by norzechowicz** [comment]
duplicated #50

**Comment by szymach** [comment]
different branch?

**Comment by norzechowicz** [comment]
thats why smart people behind the git invented cherry pick

**Comment by szymach** [comment]
Well then I can simply correct it, you don't need to close the PR right away

**Comment by norzechowicz** [comment]
I do need to close it because this PR is not valid anyway, first correct it in #50 thread, then after merge it can be cherry picked to master or master can wait for merge ``remove-fosub`` branch which was planned for version 2.0 anyway as far as I know.

**Comment by szymach** [comment]
Currently everyone using the branch `master` trying to update their dependencies will get errors, so no sense waiting around.

**Pull request closed without merging**
